name: Schedule-Test

on:
  
  workflow_dispatch:
  
    

jobs:
  show-time:

    runs-on: ubuntu-latest
    steps:
      - name: show current UTC time
        run: date -u

      - name: show local time (IST)
        run: date -d '+5 hours 30 minutes'
        
  
